server:
   port: 8084
spring:
   application:
      name: API-GATEWAY
#   could:
#      config:
#         enabled: false   
#      gateway:
#         routes:
#         - id: SMARTUSER-SERVICE
#           uri: lb://SMARTUSER-SERVICE
#           predicates:
#           - Path=/smartuser-api/**
#         - id: SMARTADDRESS-SERVICE
#           uri: lb://SMARTADDRESS-SERVICE
#           predicates:
#           - Path=/smartaddress-api/**
      
#Eureka settings:
eureka:
   instance:
      hostname: localhost
   client:
      fetch-registry: true
      register-with-eureka: true
      serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:8761/eureka     
   
#ApiGateway logging:         
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG      
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
                   