server:
   port: 8084
spring:
   application:
      name: API-GATEWAY
   could:
      gateway:
         routes:
            - id: SMARTUSER-SERVICE
              uri: lb://SMARTUSER-SERVICE
              predicates:
                 - Path=/smartuser-api/**
                 
            - id: SMARTADDRESS-SERVICE
              uri: lb://SMARTADDRESS-SERVICE
              predicates:
                 - Path=/smartaddress-api/**
      
#Eureka settings:
eureka:
   instance:
      prefer-ip-address: true
   client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
         defaultZone: http://localhost:8761/eureka      
   
#ApiGateway logging:         
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG         